/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationidologis;

import bdd.*;
import classes.Classe;
import classes.Utilisateur;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhaene
 */
public class FenetrePrincipale extends javax.swing.JFrame {
    
    Bdd bdd = new Bdd(Parametres.LIEN, Parametres.UTILISATEUR, 
             Parametres.PASSWORD);
    Connection con = bdd.connexionDatabase();
    Statement stm;
    ResultSet rs;
    
    /**
     * Creates new form FenetrePrincipale
     * @throws java.sql.SQLException
     */
    public FenetrePrincipale() throws SQLException {
        initComponents();

        tblVentes.setModel(afficher("ventes"));
        tblLocations.setModel(afficher("locations"));
        comboClasse();
        comboVendeur();
        
    }
    
    public void comboClasse() throws SQLException{
        ServiceClasse service = new ServiceClasse();
        ArrayList<Classe> liste = service.listeClasse();
        for(int i=0;i<liste.size();i++){
            cmb_classe.addItem(liste.get(i));
        }
    }
    
    public void comboVendeur() throws SQLException{
        ServiceUtilisateur service = new ServiceUtilisateur();
        ArrayList<Utilisateur> liste = service.listeUtilisateur();
        for(int i=0;i<liste.size();i++){
            cmb_utilisateur.addItem(liste.get(i));
        }
    }
    
    private DefaultTableModel afficher(String pCategorie){
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("id");
        model.addColumn("secteur");
        model.addColumn("type");
        model.addColumn("surface");
        model.addColumn("surfaceTerrain");
        model.addColumn("chambres");
        model.addColumn("pieces");
        model.addColumn("prix");
        
        try{

            model.setRowCount(0);
            stm=con.createStatement();
            switch (pCategorie) {
                case "ventes":
                    rs=stm.executeQuery("Select * from biens where categorie_id = 1");
                    break;
                case "locations":
                    rs=stm.executeQuery("Select * from biens where categorie_id = 2");
                    break;
            }
            
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("id"),rs.getString("secteur"),rs.getString("types"),
                rs.getString("surface"),rs.getString("surfaceTerrain"),rs.getString("chambres"),rs.getString("pieces"),rs.getString("prix")});
            }
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
        return model;
    }
    
    public void remplitChampsVentes() throws SQLException{
        
        rs = stm.executeQuery("select * from biens where id ="+String.valueOf(tblVentes.getValueAt(tblVentes.getSelectedRow(), 0))+";");
        rs.next();

        v_secteur.setText(rs.getString(3));
        v_type.setText(rs.getString(8));
        v_surface.setText(rs.getString(4));
        v_surfTerrain.setText(rs.getString(5));
        v_chambres.setValue(rs.getInt(6));
        v_pieces.setValue(rs.getInt(7));
        v_prix.setText(rs.getString(9));
        v_vendeur.setValue(rs.getInt(10));
        v_classe.setValue(rs.getInt(11));

    }
    
    public void remplitChampsLocations() throws SQLException{
        
        rs = stm.executeQuery("select * from biens where id ="+String.valueOf(tblLocations.getValueAt(tblLocations.getSelectedRow(), 0))+";");
        rs.next();
        
        l_secteur.setText(rs.getString(3));
        l_type.setText(rs.getString(8));
        l_surface.setText(rs.getString(4));
        l_surfTerrain.setText(rs.getString(5));
        l_chambres.setValue(rs.getInt(6));
        l_pieces.setValue(rs.getInt(7));
        l_prix.setText(rs.getString(9));
        cmb_classe.setSelectedItem(rs.getInt(11));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVentes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        v_secteur = new javax.swing.JTextField();
        v_surface = new javax.swing.JTextField();
        v_surfTerrain = new javax.swing.JTextField();
        v_prix = new javax.swing.JTextField();
        v_btn_ajout = new javax.swing.JButton();
        v_btn_suppr = new javax.swing.JButton();
        v_btn_modif = new javax.swing.JButton();
        v_type = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        v_vendeur = new javax.swing.JSpinner();
        v_classe = new javax.swing.JSpinner();
        v_pieces = new javax.swing.JSpinner();
        v_chambres = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        l_secteur = new javax.swing.JTextField();
        l_surface = new javax.swing.JTextField();
        l_surfTerrain = new javax.swing.JTextField();
        l_prix = new javax.swing.JTextField();
        l_btn_ajout = new javax.swing.JButton();
        l_btn_suppr = new javax.swing.JButton();
        l_btn_modif = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLocations = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        l_type = new javax.swing.JTextField();
        l_chambres = new javax.swing.JSpinner();
        l_pieces = new javax.swing.JSpinner();
        cmb_classe = new javax.swing.JComboBox<>();
        cmb_utilisateur = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setText("gestion des ventes");

        tblVentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVentes);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("secteur:");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("type:");

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("surface terrain:");

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel6.setText("nombre de chambre:");

        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel7.setText("nombre de pièces:");

        jLabel8.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel8.setText("prix:");

        jLabel9.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel9.setText("vendeur à charge:");

        jLabel10.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel10.setText("classe:");

        v_btn_ajout.setText("ajouter");
        v_btn_ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_btn_ajoutActionPerformed(evt);
            }
        });

        v_btn_suppr.setText("supprimer");
        v_btn_suppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_btn_supprActionPerformed(evt);
            }
        });

        v_btn_modif.setText("modifier");
        v_btn_modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_btn_modifActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel22.setText("surface:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel22))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(v_prix, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(v_surfTerrain, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(v_surface, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(v_secteur, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(v_type, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(v_vendeur)
                    .addComponent(v_classe)
                    .addComponent(v_pieces, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(v_chambres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(v_btn_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(v_btn_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(v_btn_suppr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_btn_suppr)
                    .addComponent(v_btn_modif)
                    .addComponent(v_btn_ajout))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(v_secteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(v_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(v_surface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addComponent(v_surfTerrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(v_chambres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(v_pieces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(v_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(v_vendeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(v_classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("ventes", jPanel1);

        jLabel12.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel12.setText("gestion des locations");

        jLabel13.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel13.setText("secteur:");

        jLabel14.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel14.setText("surface:");

        jLabel15.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel15.setText("surface terrain:");

        jLabel16.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel16.setText("nombre de chambre:");

        jLabel17.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel17.setText("nombre de pièces:");

        jLabel18.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel18.setText("prix:");

        jLabel19.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel19.setText("vendeur à charge:");

        jLabel20.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel20.setText("classe:");

        l_btn_ajout.setText("ajouter");
        l_btn_ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_btn_ajoutActionPerformed(evt);
            }
        });

        l_btn_suppr.setText("supprimer");
        l_btn_suppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_btn_supprActionPerformed(evt);
            }
        });

        l_btn_modif.setText("modifier");
        l_btn_modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_btn_modifActionPerformed(evt);
            }
        });

        tblLocations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLocations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLocationsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLocations);

        jLabel23.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel23.setText("type:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l_prix, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(l_surfTerrain, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(l_surface, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(l_secteur, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(l_chambres)
                            .addComponent(l_pieces)
                            .addComponent(cmb_classe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_utilisateur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(l_type, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_btn_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(l_btn_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(l_btn_suppr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_btn_suppr)
                    .addComponent(l_btn_modif)
                    .addComponent(l_btn_ajout))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(l_secteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(l_surface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addComponent(l_surfTerrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(l_chambres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(l_pieces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(l_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(cmb_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(cmb_classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("locations", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblVentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentesMouseClicked
        try {
            remplitChampsVentes();
        } catch (SQLException ex) {
            Logger.getLogger(FenetrePrincipale.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblVentesMouseClicked

    private void tblLocationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLocationsMouseClicked
        try {
            remplitChampsLocations();
        } catch (SQLException ex) {
            Logger.getLogger(FenetrePrincipale.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblLocationsMouseClicked

    private void v_btn_ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_btn_ajoutActionPerformed

        String[] colonnes= {"secteur", "types", "surface", "surfaceTerrain", "chambres", "pieces", "prix", "user_id","categorie_id","classe_id"};
        Object[] contenu={v_secteur.getText(),v_type.getText(), v_surface.getText(),v_surfTerrain.getText(),(int) v_chambres.getValue()
                ,(int) v_pieces.getValue(),v_prix.getText(),(int) v_vendeur.getValue(),1,(int) v_classe.getValue()};
        System.out.println(bdd.insert("biens", colonnes, contenu));
        tblVentes.setModel(afficher("ventes"));
    }//GEN-LAST:event_v_btn_ajoutActionPerformed

    private void l_btn_ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_btn_ajoutActionPerformed
        String[] colonnes= {"secteur", "types", "surface", "surfaceTerrain", "chambres", "pieces", "prix", "user_id","categorie_id","classe_id"};
        Classe classe = (Classe) cmb_classe.getSelectedItem();
        int classe_id = classe.getId();
        Utilisateur utilisateur = (Utilisateur) cmb_utilisateur.getSelectedItem();
        int utilisateur_id = utilisateur.getId();
        Object[] contenu={l_secteur.getText(),l_type.getText(), l_surface.getText(),l_surfTerrain.getText(),(int) l_chambres.getValue()
                ,(int) l_pieces.getValue(),l_prix.getText(),utilisateur_id,2, classe_id};
        System.out.println(bdd.insert("biens", colonnes, contenu));
        tblLocations.setModel(afficher("locations"));
    }//GEN-LAST:event_l_btn_ajoutActionPerformed

    private void l_btn_supprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_btn_supprActionPerformed
       String id = String.valueOf(tblLocations.getValueAt(tblLocations.getSelectedRow(), 0));
       System.out.println(bdd.delete("biens", id));
       tblLocations.setModel(afficher("locations"));
    }//GEN-LAST:event_l_btn_supprActionPerformed

    private void v_btn_supprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_btn_supprActionPerformed
        String id = String.valueOf(tblVentes.getValueAt(tblVentes.getSelectedRow(), 0));
        System.out.println(bdd.delete("biens", id));
        tblVentes.setModel(afficher("ventes"));
    }//GEN-LAST:event_v_btn_supprActionPerformed

    private void v_btn_modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_btn_modifActionPerformed
        String id = String.valueOf(tblVentes.getValueAt(tblVentes.getSelectedRow(), 0));
        String[] colonnes= {"secteur", "types", "surface", "surfaceTerrain", "chambres", "pieces", "prix", "user_id","categorie_id","classe_id"};
        Object[] contenu={v_secteur.getText(),v_type.getText(), v_surface.getText(),v_surfTerrain.getText(),(int) v_chambres.getValue()
                ,(int) v_pieces.getValue(),v_prix.getText(),(int) v_vendeur.getValue(),1,(int) v_classe.getValue()};
        System.out.println(bdd.updateBien("biens", colonnes, contenu, "id="+id));
        tblVentes.setModel(afficher("ventes"));
    }//GEN-LAST:event_v_btn_modifActionPerformed

    private void l_btn_modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_btn_modifActionPerformed
        String id = String.valueOf(tblLocations.getValueAt(tblLocations.getSelectedRow(), 0));
        String[] colonnes= {"secteur", "types", "surface", "surfaceTerrain", "chambres", "pieces", "prix", "user_id","categorie_id","classe_id"};
        Classe classe = (Classe) cmb_classe.getSelectedItem();
        int classe_id = classe.getId();
        Utilisateur utilisateur = (Utilisateur) cmb_utilisateur.getSelectedItem();
        int utilisateur_id = utilisateur.getId();
        Object[] contenu={l_secteur.getText(),l_type.getText(), l_surface.getText(),l_surfTerrain.getText(),(int) l_chambres.getValue()
                ,(int) l_pieces.getValue(),l_prix.getText(),utilisateur_id,2,classe_id};
        System.out.println(bdd.updateBien("biens", colonnes, contenu, "id ="+id));
        tblVentes.setModel(afficher("locations"));
    }//GEN-LAST:event_l_btn_modifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new FenetrePrincipale().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FenetrePrincipale.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> cmb_classe;
    private javax.swing.JComboBox<Object> cmb_utilisateur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton l_btn_ajout;
    private javax.swing.JButton l_btn_modif;
    private javax.swing.JButton l_btn_suppr;
    private javax.swing.JSpinner l_chambres;
    private javax.swing.JSpinner l_pieces;
    private javax.swing.JTextField l_prix;
    private javax.swing.JTextField l_secteur;
    private javax.swing.JTextField l_surfTerrain;
    private javax.swing.JTextField l_surface;
    private javax.swing.JTextField l_type;
    private javax.swing.JTable tblLocations;
    private javax.swing.JTable tblVentes;
    private javax.swing.JButton v_btn_ajout;
    private javax.swing.JButton v_btn_modif;
    private javax.swing.JButton v_btn_suppr;
    private javax.swing.JSpinner v_chambres;
    private javax.swing.JSpinner v_classe;
    private javax.swing.JSpinner v_pieces;
    private javax.swing.JTextField v_prix;
    private javax.swing.JTextField v_secteur;
    private javax.swing.JTextField v_surfTerrain;
    private javax.swing.JTextField v_surface;
    private javax.swing.JTextField v_type;
    private javax.swing.JSpinner v_vendeur;
    // End of variables declaration//GEN-END:variables
}
